### PR TITLE
Various version-related fixes, particles example

### PR DESCRIPTION
**Pull request by kristianlm**
Hi Alex!

I played around with glls a bit, and made this example while learning my way around things like `mesh-vertex-set!` and 2D. I thought it may be useful for others and I guess you can't have too many examples.

Please let me know if this is useful.

### CODE REVIEW

**Comment by AlexCharlton** [comment]
Nice example and fixes! Do you mind updating the readme to reflect the new shader version syntax?

**Comment by kristianlm** [comment]
That's strange, I made this PR just for the particles example (no GLES version). Maybe github got confused with all my forced-pushing (I make a lot of mistakes). Let's close this PR and do this all over.

**Comment by kristianlm** [comment]
Ok, I can't make a PR for a commit not on a branch. I'll make the documentation changes and update this PR (if github lets me)

**Comment by kristianlm** [comment]
Ok, github picks up my new commits automatically. Merge if that looks all right!

**Comment by AlexCharlton** [comment]
Looks good! There is a merge conflict, though, caused by my update to the readme. You'll need to merge the latest master into yours before I can merge this PR.

**Comment by kristianlm** [comment]
Done!

**Comment by AlexCharlton** [comment]
Great! Thanks!

**Pull request merged**
